# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 568dbd259a6552bce4c89303fabf4630942dd6b3c453a613406b4a630885966265640a5137fdc62c812793ff5788602be107ed03d9d328c02679f45ebb89e0ee

test:
  secret_key_base: 46ca07e141b1b132b4da9f6e1a9df25cafcb43e4e7a3a83b12cd59ecaf8aeed1cb62dcfc1d528e20d00cf34c883eec77abb1470348571c553676e3ea1906661f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
